### PR TITLE
Use wrapping sub to prevent underflow

### PR DESCRIPTION
**Pull request by casey**
Fix possible underflow when first diff is an addition, see  #3.

### CODE REVIEW

**Comment by casey** [comment]
Is wrapping sub the right behavior here? Would it be preferable to skip this test and always do `format_add` if this is the first diff?

**Comment by CAD97** [comment]
This patch is easier, as a wrapping_sub will "always" be out of bounds for the get. We could treat the first diff differently, or check for the `i=1` case explicitly, but I think treating every case the same is better.

**Comment by casey** [comment]
I think that's totally reasonable. An alternative is to do:

```
if let Some(Rem(removed)) = i.checked_sub(1).map(|i| &diffs[i]) {
```

Which is weird, but maybe slightly more explicit.

**Comment by casey** [comment]
What do you think about my proposal to use `checked_sub`? I think it's fine as written too, so please feel free to merge that if you prefer it.

**Comment by CAD97** [comment]
Actually, yes, `checked_sub` is the correct way to do it. If you update the patch to use that I can probably push a patch update today or tomorrow.

**Comment by casey** [comment]
Great, just pushed a diff w/`checked_sub` instead of `wrapping_sub`

**Comment by casey** [comment]
Sweet!

**Pull request merged**
